### ISSUE TITLE
upload_dir does not complain when source directory not found

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/ctadata#35]
as @andriineronov finds

when upload is running, target directory is ignored somehow?..

**Comment by Ph0tonic** [comment]
+1 for this issue.

**Comment by volodymyrss** [comment]
@andriineronov sat that if the source directory is not there, there was no error message. I can not immediately reproduce it. Can you try different options and look into the code to understand if there is a corner case which corresponds to the experience of @andriineronov ?
